modules:
  - type: script
    scripts:
      - install-kind.sh
      - install-kubectl.sh
      - install-kubectx.sh
      - install-kubens.sh
      - install-zellij.sh
      - add-gcloud-repo.sh

  - type: rpm-ostree
    repos: 
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
    install:
      - nautilus-open-any-terminal
      - docker
      - starship
      - distrobox
      - zsh
      - jq
      - ripgrep
      - bat
      - git
      - neovim
      - helm
      - stow
      - lazygit
      - azure-cli
      - google-cloud-cli
      - google-cloud-cli-gke-gcloud-auth-plugin
      - nodejs
      - dotnet-sdk-8.0
      - dotnet-sdk-7.0
      - dotnet-sdk-6.0
      - binutils
      - gcc
      - gcc-c++
      - g++
      - glibc
      - glibc-devel
      - lm_sensors
      - libgtop2-devel
    remove:
      - nvtop

  - type: script
    scripts:
      - ld-symlink-workaround.sh
