# image will be published to ghcr.io/<user>/<name>
name: uz-os
description: This is my work OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - from-file: modules/fonts.yml
  - from-file: modules/cli-tools.yml
  - from-file: modules/gui-tools.yml

  - type: gschema-overrides
    include:
      - zz1-defaults.gschema.override

  - type: systemd
    system:
      enabled:
        - os-groups.service
        - os-shell.service
        - dconf-update.service
        - flatpak-theme.service

  - type: yafti

  - type: signing 
